<html>
   <head>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="./CSS/theme.css">
       <title>
           Chicken
       </title>
       <style>
           .logo{
               width: 100%;
               text-align: center;
           }
           img{
               
               width: 20%;
               height: 40%;
           }
           .logoimg{
               width: 18%;
               height: 18%;
           }
           #btnlogin,#btndaftar{
               width: 70%;
               padding: 4%;
           }
           .form-control{
               width: 70%;
           }
           #coordinate,#btnlogin{
               margin-left: 8%;
               margin-top: 3%;
           }
           #btndaftar{
               margin-top: 5%;
               width: 100%;
           }
           .contact{
               text-align: right;
               margin-top: 5%;
           }
           p{
               float: left;
               font-size: 12pt;
           }
           #button{
               padding-top: 9px;
                padding-bottom: 9px;
           }
           .contentlist{
                width: 70%;
                height: 60%;
                padding: 10px;
                padding-top: 20px;
                margin: 0 auto;
                text-align: center;
            }
           .add-on .input-group-btn > .btn {
              border-left-width:0;left:-2px;
              -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
              box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
            }
            /* stop the glowing blue shadow */
            .add-on .form-control:focus {
             box-shadow:none;
             -webkit-box-shadow:none; 
             border-color:#cccccc; 
            }
            .navbar-nav:last-child{ border-right:0}
           h3{
               padding-bottom: 2%;
           }
           .info{
               float: right;
               width: 78%;
               text-align: left;
           }
           .item{
               padding: 1%;
           }
       </style>
   </head>
    <body>
        <div class="logo">
            <img src="IMAGES/LOGO.PNG" class="logoimg">
        </div>
        <div class="contentlist">
            <div class="box">
               <h3>Promo Debit</h3>
                <form class="navbar-form" role="search">
                <div class="input-group add-on">
                  <input class="form-control" placeholder="Search" name="srch-term" id="srch-term" type="text">
                  <div class="input-group-btn">
                    <button class="btn btn-default" type="submit" id="button"><i class="glyphicon glyphicon-search"></i></button>
                  </div>
                </div>
              </form>
              <div class="item">
                 
                  <img src="./IMAGES/resto.jpg">
                  <div class="info">
                  <a href="resto.PHP"><h4>Promo Restoran ini</h4></a>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus diam quis porta tincidunt. Quisque eu placerat felis. Integer id libero vitae diam tincidunt pretium.</p>
                  <h4>Price : IDR 50,000</h4>
                  </div>
              </div>
              <div class="item">
                 
                  <img src="./IMAGES/resto.jpg">
                  <div class="info">
                  <a href="resto.PHP"><h4>Promo Restoran ini</h4></a>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus diam quis porta tincidunt. Quisque eu placerat felis. Integer id libero vitae diam tincidunt pretium.</p>
                  <h4>Price : IDR 50,000</h4>
                  </div>
              </div>
              <div class="item">
                 
                  <img src="./IMAGES/resto.jpg">
                  <div class="info">
                  <a href="resto.PHP"><h4>Promo Restoran ini</h4></a>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus diam quis porta tincidunt. Quisque eu placerat felis. Integer id libero vitae diam tincidunt pretium.</p>
                  <h4>Price : IDR 50,000</h4>
                  </div>
              </div>
              <div class="item">
                 
                  <img src="./IMAGES/resto.jpg">
                  <div class="info">
                  <a href="resto.PHP"><h4>Promo Restoran ini</h4></a>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus diam quis porta tincidunt. Quisque eu placerat felis. Integer id libero vitae diam tincidunt pretium.</p>
                  <h4>Price : IDR 50,000</h4>
                  </div>
              </div>
              <div class="item">
                 
                  <img src="./IMAGES/resto.jpg">
                  <div class="info">
                  <a href="resto.PHP"><h4>Promo Restoran ini</h4></a>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus diam quis porta tincidunt. Quisque eu placerat felis. Integer id libero vitae diam tincidunt pretium.</p>
                  <h4>Price : IDR 50,000</h4>
                  </div>
              </div>
              <div class="item">
                 
                  <img src="./IMAGES/resto.jpg">
                  <div class="info">
                  <a href="resto.PHP"><h4>Promo Restoran ini</h4></a>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus diam quis porta tincidunt. Quisque eu placerat felis. Integer id libero vitae diam tincidunt pretium.</p>
                  <h4>Price : IDR 50,000</h4>
                  </div>
              </div>
            </div>
        </div>
    </body>
</html>