<html>
   <head>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
       <title>
           Chicken
       </title>
       <style>
           .logo{
               width: 100%;
               padding-top: 1%;
               text-align: center;
           }
           .logoimg{
               width: 18%;
               height: 18%;
           }
       </style>
   </head>
    <body>
        <div class="logo">
            <img src="IMAGES/LOGO.PNG" class="logoimg">
        </div>
        <div class="content"></div>
    </body>
</html>