<html>
   <head>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="./CSS/theme.css">
       <title>
           Chicken
       </title>
       <style>
           .logo{
               width: 100%;
               text-align: center;
           }
           .logoimg{
               width: 18%;
               height: 18%;
           }
           #btnlogin,#btndaftar{
               padding: 3%;
           }
           .form-control{
               width: 70%;
           }
           #coordinate,#btnlogin{
               margin-left: 8%;
               margin-top: 3%;
           }
           #btndaftar{
               margin-top: 5%;
           }
           .contact{
               text-align: right;
               margin-top: 5%;
           }
           p{
               font-size: 12pt;
           }
           img{
               
               width: 30%;
               height: 70%;
           }
           .info{
               float: right;
               width: 69%;
               text-align: left;
           }
           button{
               margin-left: 19%;
               width: 50%;
               font-size: 18pt;
           }
       </style>
   </head>
    <body>
        <div class="logo">
            <img src="IMAGES/LOGO.PNG" class="logoimg">
        </div>
        <div class="content">
        <h3>Restoran : Promo Restoran ini</h3>
              <div class="item">
                 
                  <img src="./IMAGES/food.jpg">
                  <div class="info">
                  <a href="restodetail.php"><h4>Promo Restoran ini</h4></a>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse maximus diam quis porta tincidunt. Quisque eu placerat felis. Integer id libero vitae diam tincidunt pretium.</p>
                  <a href="home.PHP"><button type="button" class="btn btn-info" id="btndaftar">Redeem</button>
                  </a>
                  </div>
              </div>
        </div>
    </body>
</html>